#!/usr/bin/env bash
set -euo pipefail

# niteshift-setup.sh
# Idempotent setup script for umami repository
# Detects and installs only required dependencies

# ============================================================================
# Configuration
# ============================================================================

LOG_FILE="${NITESHIFT_LOG_FILE:-}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ============================================================================
# Logging utilities
# ============================================================================

log() {
  local msg="$1"
  if [[ -n "$LOG_FILE" ]]; then
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $msg" | tee -a "$LOG_FILE"
  else
    echo "$msg"
  fi
}

error() {
  log "ERROR: $1" >&2
  exit 1
}

# ============================================================================
# Dependency detection and installation
# ============================================================================

check_command() {
  command -v "$1" >/dev/null 2>&1
}

setup_nodejs() {
  log "==> Setting up Node.js environment..."

  if ! check_command node; then
    error "Node.js is not installed. Please install Node.js (v18 or higher) first."
  fi

  local node_version
  node_version=$(node --version | sed 's/v//')
  log "Found Node.js version: $node_version"

  # Enable corepack for pnpm (preferred method)
  if check_command corepack; then
    log "Enabling corepack for pnpm..."
    corepack enable || log "Warning: Could not enable corepack (may need sudo)"
  fi

  # Check if pnpm is available
  if ! check_command pnpm; then
    if check_command corepack; then
      log "Installing pnpm via corepack..."
      corepack prepare pnpm@latest --activate || error "Failed to install pnpm via corepack"
    else
      error "pnpm is not installed and corepack is not available. Please install pnpm: npm install -g pnpm"
    fi
  fi

  log "Found pnpm version: $(pnpm --version)"
}

install_dependencies() {
  log "==> Installing project dependencies..."

  if [[ ! -f "$SCRIPT_DIR/pnpm-lock.yaml" ]]; then
    error "pnpm-lock.yaml not found"
  fi

  # Run pnpm install (idempotent)
  cd "$SCRIPT_DIR"
  pnpm install --frozen-lockfile || error "Failed to install dependencies"

  log "Dependencies installed successfully"
}

setup_database() {
  log "==> Setting up database..."

  # Check if DATABASE_URL is set
  if [[ -z "${DATABASE_URL:-}" ]]; then
    log "DATABASE_URL not set. Checking for docker-compose..."

    if [[ -f "$SCRIPT_DIR/docker-compose.yml" ]] && check_command docker; then
      log "Starting PostgreSQL via docker-compose..."

      # Start only the database service
      docker compose -f "$SCRIPT_DIR/docker-compose.yml" up -d db || \
        error "Failed to start database container"

      # Wait for database to be ready (with timeout)
      log "Waiting for database to be ready..."
      local max_attempts=30
      local attempt=0

      while [[ $attempt -lt $max_attempts ]]; do
        if docker compose -f "$SCRIPT_DIR/docker-compose.yml" exec -T db pg_isready -U umami -d umami >/dev/null 2>&1; then
          log "Database is ready"
          break
        fi

        attempt=$((attempt + 1))
        if [[ $attempt -ge $max_attempts ]]; then
          error "Database failed to become ready within timeout"
        fi

        sleep 1
      done

      # Set DATABASE_URL for this session
      export DATABASE_URL="postgresql://umami:umami@localhost:5432/umami"
      log "DATABASE_URL set to: $DATABASE_URL"
    else
      log "Warning: DATABASE_URL not set and docker-compose/docker not available"
      log "You will need to set DATABASE_URL manually before running the application"
      log "Example: export DATABASE_URL=postgresql://user:pass@localhost:5432/umami"
      return 0
    fi
  else
    log "DATABASE_URL is already set"
  fi

  # Generate Prisma client
  log "Generating Prisma client..."
  cd "$SCRIPT_DIR"
  pnpm run build-db-client || error "Failed to generate Prisma client"

  # Run database migrations
  if [[ -n "${DATABASE_URL:-}" ]]; then
    log "Running database migrations..."
    pnpm run update-db || log "Warning: Database migrations failed (database may not be accessible yet)"
  fi
}

setup_environment() {
  log "==> Setting up environment variables..."

  # Check if .env file exists
  if [[ ! -f "$SCRIPT_DIR/.env" ]]; then
    log "No .env file found. Creating one with defaults..."

    # Generate a random APP_SECRET if not set
    local app_secret="${APP_SECRET:-$(openssl rand -hex 32 2>/dev/null || echo "change-me-$(date +%s)")}"

    cat > "$SCRIPT_DIR/.env" <<EOF
# Generated by niteshift-setup.sh
# Update these values as needed

DATABASE_URL=postgresql://umami:umami@localhost:5432/umami
DATABASE_TYPE=postgresql
APP_SECRET=${app_secret}

# Optional: Uncomment to enable Redis caching
# REDIS_URL=redis://localhost:6379
EOF

    log "Created .env file with default values"
    log "IMPORTANT: Please review and update .env with your actual configuration"
  else
    log ".env file already exists"
  fi
}

build_application() {
  log "==> Building application assets..."

  cd "$SCRIPT_DIR"

  # Build tracker (required for the application)
  if [[ -f "$SCRIPT_DIR/rollup.tracker.config.js" ]]; then
    log "Building tracker..."
    pnpm run build-tracker || error "Failed to build tracker"
  fi

  # Build geo database (optional but recommended)
  log "Building geo database..."
  pnpm run build-geo || log "Warning: Failed to build geo database (non-critical)"

  log "Application assets built successfully"
}

# ============================================================================
# Main setup flow
# ============================================================================

main() {
  log "============================================"
  log "Umami Setup Script"
  log "============================================"
  log ""

  setup_nodejs
  install_dependencies
  setup_environment
  setup_database
  build_application

  log ""
  log "============================================"
  log "Setup completed successfully!"
  log "============================================"
  log ""
  log "Next steps:"
  log "  1. Review and update .env file with your configuration"
  log "  2. Run 'pnpm run dev' to start the development server"
  log "  3. Run 'pnpm run build' to build for production"
  log ""
  log "For more information, visit: https://umami.is/docs"
}

main "$@"
